# Generated by Django 4.1.3 on 2022-11-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='registered',
            field=models.BooleanField(default=True),
        ),
    ]
