# Generated by Django 4.1.3 on 2022-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='additional_info',
            field=models.TextField(default='a'),
        ),
    ]
